#  El Problema

Vamos a utilizar los datos de la competición de predicción de los datos del Dengue. Mas información en [enlace](https://www.drivendata.org/competitions/44/dengai-predicting-disease-spread/)

El objetivo del ejercicio es por un lado jugar con una red neuronal para resolver un problema de regresión y por otro participar en una competición de datos. 


# Setting Preliminares

Antes de empezar cualquier análisis hay que asegurar que las librerías básicas y de uso general (numpy, pandas, etc.) están correctamente importadas. 

In [1]:
# carga de datos
import pandas as pd
import io
from google.colab import files
# manipulación y visualización
import matplotlib.pyplot as plt
import numpy as np
import itertools
import seaborn as sns



# Carga de Datos

En primer lugar cargamos los datos dentro del entorno con las funcionalidades que nos permite Google Colab

In [2]:
def upload_files ():
  uploaded = files.upload()
  for fn in uploaded.keys():
    print('User uploaded file "{name}" with length {length} bytes'.format(
        name=fn, length=len(uploaded[fn])))
    df = pd.read_csv(io.StringIO(uploaded[fn].decode('utf-8')))
    return df

En primer lugar subimos los datos de entrenamiento sin campo objetivo (dengue_features_train)


In [3]:
train_feat = upload_files()
train_feat.head()

Saving dengue_features_train.csv to dengue_features_train.csv
User uploaded file "dengue_features_train.csv" with length 287139 bytes


city  year  ...  station_min_temp_c station_precip_mm
0   sj  1990  ...                20.0              16.0
1   sj  1990  ...                22.2               8.6
2   sj  1990  ...                22.8              41.4
3   sj  1990  ...                23.3               4.0
4   sj  1990  ...                23.9               5.8

[5 rows x 24 columns]

In [4]:
train_feat.shape

(1456, 24)

Posteriormente subimos los datos que únicamente nos proporcionan el número de casos de dengue para las semanas de entrenamiento (dengue_labels_train)

In [5]:
train_labels = upload_files()
train_labels.head()

Saving dengue_labels_train.csv to dengue_labels_train.csv
User uploaded file "dengue_labels_train.csv" with length 19582 bytes


city  year  weekofyear  total_cases
0   sj  1990          18            4
1   sj  1990          19            5
2   sj  1990          20            4
3   sj  1990          21            3
4   sj  1990          22            6

Mezclamos los dos conjuntos de datos para tenerlos en un único dataframe

In [6]:
train = pd.merge(train_feat,train_labels,on=['city', 'year', 'weekofyear'])

train.head()


city  year  weekofyear  ... station_min_temp_c  station_precip_mm  total_cases
0   sj  1990          18  ...               20.0               16.0            4
1   sj  1990          19  ...               22.2                8.6            5
2   sj  1990          20  ...               22.8               41.4            4
3   sj  1990          21  ...               23.3                4.0            3
4   sj  1990          22  ...               23.9                5.8            6

[5 rows x 25 columns]

Finalmente subimos los datos para generar la evaluación final (dengue_features_test)

In [7]:
test = upload_files()
test.head()

Saving dengue_features_test.csv to dengue_features_test.csv
User uploaded file "dengue_features_test.csv" with length 82465 bytes


city  year  ...  station_min_temp_c station_precip_mm
0   sj  2008  ...                21.7              75.2
1   sj  2008  ...                22.2              34.3
2   sj  2008  ...                22.8               3.0
3   sj  2008  ...                24.4               0.3
4   sj  2008  ...                23.3              84.1

[5 rows x 24 columns]

In [8]:
test.shape

(416, 24)

# Preproceso

Aquí irían todas las funciones y transformaciones que permitieran el uso de las variables en los siguientes clasificadores, por ejemplo la transformación de las variables categóricas en numéricas, etc.

In [9]:
train.drop("week_start_date", axis = 1, inplace = True)
test.drop("week_start_date", axis = 1, inplace = True)
train.head()


city  year  weekofyear  ...  station_min_temp_c  station_precip_mm  total_cases
0   sj  1990          18  ...                20.0               16.0            4
1   sj  1990          19  ...                22.2                8.6            5
2   sj  1990          20  ...                22.8               41.4            4
3   sj  1990          21  ...                23.3                4.0            3
4   sj  1990          22  ...                23.9                5.8            6

[5 rows x 24 columns]

Trataremos los valores perdidos que los hay dado que nos evitarían tener un modelo de los datos que tenemos.

In [10]:
pd.isnull(train).sum()

city                                       0
year                                       0
weekofyear                                 0
ndvi_ne                                  194
ndvi_nw                                   52
ndvi_se                                   22
ndvi_sw                                   22
precipitation_amt_mm                      13
reanalysis_air_temp_k                     10
reanalysis_avg_temp_k                     10
reanalysis_dew_point_temp_k               10
reanalysis_max_air_temp_k                 10
reanalysis_min_air_temp_k                 10
reanalysis_precip_amt_kg_per_m2           10
reanalysis_relative_humidity_percent      10
reanalysis_sat_precip_amt_mm              13
reanalysis_specific_humidity_g_per_kg     10
reanalysis_tdtr_k                         10
station_avg_temp_c                        43
station_diur_temp_rng_c                   43
station_max_temp_c                        20
station_min_temp_c                        14
station_pr

Los vamos a procesar de forma automática completandolos con el método ffill (con el valor previo)

In [11]:
# ffill: propagate last valid observation forward to next valid backfill
# Otra Opción: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.interpolate.html#pandas.DataFrame.interpolate
train.fillna(method='ffill', inplace=True)
pd.isnull(train).any()

city                                     False
year                                     False
weekofyear                               False
ndvi_ne                                  False
ndvi_nw                                  False
ndvi_se                                  False
ndvi_sw                                  False
precipitation_amt_mm                     False
reanalysis_air_temp_k                    False
reanalysis_avg_temp_k                    False
reanalysis_dew_point_temp_k              False
reanalysis_max_air_temp_k                False
reanalysis_min_air_temp_k                False
reanalysis_precip_amt_kg_per_m2          False
reanalysis_relative_humidity_percent     False
reanalysis_sat_precip_amt_mm             False
reanalysis_specific_humidity_g_per_kg    False
reanalysis_tdtr_k                        False
station_avg_temp_c                       False
station_diur_temp_rng_c                  False
station_max_temp_c                       False
station_min_t

Y aplicamos lo mismo para el test

In [12]:
test.fillna(method='ffill', inplace=True)
pd.isnull(test).any()

city                                     False
year                                     False
weekofyear                               False
ndvi_ne                                  False
ndvi_nw                                  False
ndvi_se                                  False
ndvi_sw                                  False
precipitation_amt_mm                     False
reanalysis_air_temp_k                    False
reanalysis_avg_temp_k                    False
reanalysis_dew_point_temp_k              False
reanalysis_max_air_temp_k                False
reanalysis_min_air_temp_k                False
reanalysis_precip_amt_kg_per_m2          False
reanalysis_relative_humidity_percent     False
reanalysis_sat_precip_amt_mm             False
reanalysis_specific_humidity_g_per_kg    False
reanalysis_tdtr_k                        False
station_avg_temp_c                       False
station_diur_temp_rng_c                  False
station_max_temp_c                       False
station_min_t

También tenemos que transformar nuestras variables categóricas, en este caso una única variable que es la ciudad para lo que vamos a utilizar un *binarizador* para train y para test

In [13]:
from sklearn import preprocessing
lb = preprocessing.LabelBinarizer()
train['city_bin'] = lb.fit_transform(train['city'])
test['city_bin'] = lb.fit_transform(test['city'])

In [14]:
train.tail()

city  year  weekofyear  ...  station_precip_mm  total_cases  city_bin
1451   iq  2010          21  ...               27.0            5         0
1452   iq  2010          22  ...               36.6            8         0
1453   iq  2010          23  ...                7.4            1         0
1454   iq  2010          24  ...               16.0            1         0
1455   iq  2010          25  ...               20.4            4         0

[5 rows x 25 columns]

Hay que seleccionar características, pueden ser todas, pero eso normalmente no es una buena idea, por lo que aquí dejaremos algunas seleccionadas.

In [15]:
selected_features = ['reanalysis_specific_humidity_g_per_kg', 'reanalysis_dew_point_temp_k', 
                 'station_avg_temp_c', 'station_min_temp_c']

Normalizamos los datos a partir de los coeficientes mínimo y máximo de la colección de entrenamiento.

**(Es opcional y no siempre efectivo)**

In [16]:
from sklearn.preprocessing import MinMaxScaler
# performin min-max scaling each continuous feature column to the range [0, 1]
scaler = MinMaxScaler()
X_train = scaler.fit_transform(train[selected_features])
X_test = scaler.transform(test[selected_features])
y_train = train['total_cases']


# Construcción y evaluación preliminar del modelo

In [18]:
from sklearn import linear_model
model = linear_model.LinearRegression()
model.fit(X_train, y_train)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

# Generación del Resultado Final

Generamos el fichero de salida segun el Submission format

* Realizamos la predicción sobre el test

In [19]:
y_pred = model.predict(X_test)

In [20]:
y_pred

array([ 25.06379009,  29.66502706,  31.71595663,  43.78861089,
        35.91356158,  48.98600874,  36.65691557,  41.46994145,
        38.03226533,  47.21983447,  40.40149043,  55.26418902,
        41.50037817,  46.10677278,  36.6084963 ,  43.53840459,
        38.83339625,  38.35240756,  39.26705283,  29.16888669,
        40.41542296,  29.76442752,  22.39307521,  41.84902089,
        30.9576386 ,  35.41705319,  39.94156411,  42.70291184,
        39.37127397,  35.86212756,  33.44942516,  24.01866179,
        29.7079741 ,  25.42490693,  15.67287652,  15.67287652,
        15.88919674,  30.50479935,  27.00408496,  26.40760293,
        27.21238137,  26.57127183,  24.80337951,  16.71541157,
        25.30137909,  21.16374371,  17.25305029,  19.24466784,
        16.50323884,  24.40641963,  32.90386301,  28.35788315,
        29.16124461,  29.18808217,  38.36852973,  34.34572346,
        38.99817745,  35.16425444,  40.10293956,  42.97721303,
        41.67790538,  52.70353895,  36.86337983,  52.83

* Redondeamos el resultado

In [21]:
# round the result and cast to int
import numpy as np
y = np.rint(y_pred) # round
y = y.astype(int) # cast to int
res = np.hstack(y)

res

array([ 25,  30,  32,  44,  36,  49,  37,  41,  38,  47,  40,  55,  42,
        46,  37,  44,  39,  38,  39,  29,  40,  30,  22,  42,  31,  35,
        40,  43,  39,  36,  33,  24,  30,  25,  16,  16,  16,  31,  27,
        26,  27,  27,  25,  17,  25,  21,  17,  19,  17,  24,  33,  28,
        29,  29,  38,  34,  39,  35,  40,  43,  42,  53,  37,  53,  40,
        36,  49,  45,  49,  55,  39,  31,  44,  37,  47,  51,  47,  39,
        44,  46,  31,  37,  34,  37,  36,  29,  33,  33,  26,  18,  29,
        35,  13,  24,  25,  28,  31,  11,  19,  26,  36,  25,  20,  32,
        33,  29,  36,  43,  37,  42,  43,  45,  33,  33,  38,  33,  32,
        29,  43,  41,  43,  41,  37,  41,  38,  43,  40,  43,  37,  41,
        38,  30,  33,  32,  28,  20,   5,  34,  21,  33,  19,  24,  29,
        21,  21,  24,  33,  29,  20,  18,  16,  18,  19,  26,  27,  31,
        34,  37,  34,  21,  18,  40,  20,  28,  25,  30,  39,  34,  32,
        46,  39,  28,  33,  40,  30,  42,  49,  32,  39,  36,  3

In [22]:
y_pred_no_neg = res.copy()

In [23]:
y_pred_no_neg[y_pred < 0] = 0
y_pred_no_neg

array([25, 30, 32, 44, 36, 49, 37, 41, 38, 47, 40, 55, 42, 46, 37, 44, 39,
       38, 39, 29, 40, 30, 22, 42, 31, 35, 40, 43, 39, 36, 33, 24, 30, 25,
       16, 16, 16, 31, 27, 26, 27, 27, 25, 17, 25, 21, 17, 19, 17, 24, 33,
       28, 29, 29, 38, 34, 39, 35, 40, 43, 42, 53, 37, 53, 40, 36, 49, 45,
       49, 55, 39, 31, 44, 37, 47, 51, 47, 39, 44, 46, 31, 37, 34, 37, 36,
       29, 33, 33, 26, 18, 29, 35, 13, 24, 25, 28, 31, 11, 19, 26, 36, 25,
       20, 32, 33, 29, 36, 43, 37, 42, 43, 45, 33, 33, 38, 33, 32, 29, 43,
       41, 43, 41, 37, 41, 38, 43, 40, 43, 37, 41, 38, 30, 33, 32, 28, 20,
        5, 34, 21, 33, 19, 24, 29, 21, 21, 24, 33, 29, 20, 18, 16, 18, 19,
       26, 27, 31, 34, 37, 34, 21, 18, 40, 20, 28, 25, 30, 39, 34, 32, 46,
       39, 28, 33, 40, 30, 42, 49, 32, 39, 36, 35, 35, 37, 31, 33, 37, 37,
       31, 27, 35, 29, 30, 31, 25, 29, 20, 24, 25, 28, 20, 28, 29, 32, 30,
       32, 32, 39, 35, 22, 42, 35, 41, 42, 42, 42, 47, 54, 50, 47, 35, 51,
       47, 47, 43, 33, 51

* Generamos el fichero de salida

In [24]:
# generate output
output = pd.DataFrame({ 'city': test['city'], 'year': test['year'], 'weekofyear': test['weekofyear'], 
                       'total_cases': y_pred_no_neg})


from google.colab import files

with open('result.csv', 'w') as f:
  output.to_csv(f,  index = False)
  

files.download('result.csv')

output.head()


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

city  year  weekofyear  total_cases
0   sj  2008          18           25
1   sj  2008          19           30
2   sj  2008          20           32
3   sj  2008          21           44
4   sj  2008          22           36